import matplotlib.pyplot as plt

LEGEND_ELEMENTS = [
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="green",
        markersize=8,
        label="Spawn Nodes",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="red",
        markersize=8,
        label="Destination Nodes",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="blue",
        markersize=8,
        label="Intersection Nodes",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="orange",
        markersize=8,
        label="Stoplight (Group 0 Active)",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="purple",
        markersize=8,
        label="Stoplight (Group 1 Active)",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="cyan",
        markersize=8,
        label="Stoplight (Group 2 Active)",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="#4169E1",
        markersize=6,
        label="Cars from 8_26",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="#32CD32",
        markersize=6,
        label="Cars from 18_2",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="#FF1493",
        markersize=6,
        label="Cars from 2_14",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="#FFD700",
        markersize=6,
        label="Cars from 2_12",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="#9932CC",
        markersize=6,
        label="Cars from 22_4",
    ),
    plt.Line2D(
        [0],
        [0],
        marker="o",
        color="w",
        markerfacecolor="#FF4500",
        markersize=6,
        label="Cars from 30_15",
    ),
    plt.Line2D(
        [0],
        [0],
        marker=">",
        color="red",
        markerfacecolor="red",
        markersize=8,
        label="Yield Connection",
    ),
]
